[package]
name = "mc-client"
version = "0.1.0"
edition = "2024"

[dependencies]
directories = "6.0"
futures-util = "0.3"
gpui = "0.2.2"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "stream"] }
rust-embed = "8.12.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha1 = "0.10"
thiserror = "2.0"
tokio = { version = "1.0", features = ["fs", "io-util", "rt"] }
uuid = { version = "1.0", features = ["v4"] }
zip = { version = "4.0", default-features = false, features = ["deflate"] }
